# Project: vote_X
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Users/Object/tomisin/Downloads/MinGW/lib" -L"C:/Users/Object/tomisin/Downloads/MinGW/x86_64-w64-mingw32/lib" -static-libstdc++ -static-libgcc -std=c++17 -lBox2D -lopengl32 -lglu32 -lglut64
INCS     = -I"C:/Users/Object/tomisin/Downloads/MinGW/include" -I"C:/Users/Object/tomisin/Downloads/MinGW/x86_64-w64-mingw32/include" -I"C:/Users/Object/tomisin/Downloads/MinGW/lib/gcc/x86_64-w64-mingw32/7.3.0/include"
CXXINCS  = -I"C:/Users/Object/tomisin/Downloads/MinGW/include" -I"C:/Users/Object/tomisin/Downloads/MinGW/x86_64-w64-mingw32/include" -I"C:/Users/Object/tomisin/Downloads/MinGW/lib/gcc/x86_64-w64-mingw32/7.3.0/include"
BIN      = vote_X.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
